# Generated by Django 5.1 on 2024-08-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_date_article_description_article_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contenido',
            new_name='content',
        ),
    ]
